# Generated by Django 3.0.4 on 2020-03-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.CharField(max_length=500)),
                ("publication_date", models.DateField()),
                ("isbn_number", models.CharField(max_length=60)),
                ("pages", models.IntegerField()),
                ("pub_language", models.CharField(max_length=40)),
                ("front_cover", models.URLField()),
            ],
        ),
    ]
